media: images
content:
  - name: siteSettings
    label: Site Settings
    path: data/settings.yml
    type: file
    fields:
      - name: closed_message
        label: Closed Message
        type: text
        default: "Sorry we are closed!"