media: images
content:
  - name: siteSettings
    label: Site Settings
    path: data/settings.yml
    type: file
    fields:
      - name: closed_message
        label: Closed Message
        type: textarea
        language: html
        default: "Anm. (Ordination) <br> von 29.07 bis 16.08 geschlossen."