media: images
content:
  - name: siteSettings
    label: Site Settings
    path: _data/settings.yml
    type: file
    fields:
      - name: is_closed
        label: Is Closed
        type: boolean
        default: false